import Head from "next/head";
import Header from "../components/Header";
import Timer from "../components/Pomodoro";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <Header />
        <div className="flex items-center mt-28 gap-10 justify-center">
          <Image src="/pomodoro.png" width={300} height={300} alt="Pomodoro" />
          <Timer />
        </div>
      </main>
    </>
  );
}
